#!/usr/bin/env node
 //here are some usefull test

require('../l-string');


console.log("leo".isUpper())
console.log("leo".isLower())
console.log("leo".isAlpha())
console.log("leo".isDigit())
console.log("leo".isAlphanumeric())
console.log("leo".isEmpty())
console.log("leo".isSpace())
console.log("leo".isSubString("le"))
console.log("leo".multiply(2))
console.log("leo".rSlice(2, 4))
console.log("leo".dummyCount("e"))
console.log("acb!@#$%^&*()_+".ord())
console.log("+".ord())
console.log("95".chr())
console.log("leo".capitalize())
console.log("leo".getCharPosition("e"))
console.log("leo".reverse())
console.log("leo".title())
console.log("leo".lSplit("e", 1))
console.log("leo".rSplit("o", 1))
console.log("leo".startsWith("o"))
console.log("leo".endsWith("o"))
console.log("leo".swapCase())
console.log("leo   ".trim())
console.log("leo   ".trimPrefix("eo"))
console.log("leo".rConCat("a"))
console.log("leo   ".lConCat("a"))
console.log("leo   ".lReplace("eo", "1231"))
console.log("leo   ".rReplace("eo", "1231"))
console.log("-".join("leo"))
console.log("leo   ".toCharArray())
console.log("leo   ".insert("eo", 2))
console.log("leo   ".remove("eo"))
console.log("leo   ".center(2, "-"))
console.log("leo   ".lJust(2, "-"))
console.log("leo   ".rJust(2, "-"))
console.log("leoanrdo esparis, leonardo esparis".smartCount("leo", "l1", 20))
console.log("leoanrdo esparis, leonardo esparis".smartCount("leo", "l1", "1o"))
