#!/usr/bin/env node

require('../l-string')(true);


console.log("isUpper: ", "leo".isUpper())
console.log("isLower: ", "leo".isLower())
console.log("isAlpha: ", "leo".isAlpha())
console.log("isDigit: ", "leo".isDigit())
console.log("isAlphanumeric: ", "leo".isAlphanumeric())
console.log("isEmpty: ", "leo".isEmpty())
console.log("isSpace: ", "leo".isSpace())
console.log("isSubString: ", "leo".isSubString("le"))
console.log("multiply: ", "leo".multiply(2))
console.log("rSlice: ", "leo".rSlice(2, 4))
console.log("dummyCount: ", "leo".dummyCount("e"))
console.log("ord: ", "acb!@#$%^&*()_+".ord())
console.log("ord: ", "+".ord())
console.log("chr: ", "95".chr())
console.log("capitalize: ", "leo".capitalize())
console.log("getCharPosition: ", "leo".getCharPosition("e"))
console.log("reverse: ", "leo".reverse())
console.log("title: ", "leo".title())
console.log("lSplit: ", "leo".lSplit("e", 1))
console.log("rSplit: ", "leo".rSplit("o", 1))
console.log("startsWith: ", "leo".startsWith("o"))
console.log("endsWith: ", "leo".endsWith("o"))
console.log("swapCase: ", "leo".swapCase())
console.log("trim: ", "leo   ".trim())
console.log("trimPrefix: ", "leo   ".trimPrefix("eo"))
console.log("rConCat: ", "leo".rConCat("a"))
console.log("lConCat: ", "leo   ".lConCat("a"))
console.log("lReplace: ", "leo   ".lReplace("eo", "1231"))
console.log("rReplace: ", "leo   ".rReplace("eo", "1231"))
console.log("join: ", "-".join("leo"))
console.log("toCharArray: ", "leo   ".toCharArray())
console.log("insert: ", "leo   ".insert("eo", 2))
console.log("remove: ", "leo   ".remove("eo"))
console.log("center: ", "leo   ".center(2, "-"))
console.log("lJust: ", "leo   ".lJust(2, "-"))
console.log("rJust: ", "leo   ".rJust(2, "-"))
console.log("smartCount: ", "leoanrdo esparis, leonardo esparis".smartCount("leo", "l1", 20))
console.log("smartCount: ", "leoanrdo esparis, leonardo esparis".smartCount("leo", "l1", "1o"))
